### ISSUE TITLE
cd-percentage-bar-changelog 

### ISSUE THREAD

**Issue by Zafer83** [CodyHouse/cd-percentage-bar-changelog#1]
Hi,

i tried it now several times in different pages. The Percentage bar will not shown. Either it is a css bug or the description how to use this is not clear.

please help.
![Bildschirmfoto 2022-01-12 um 20 39 35](https://user-images.githubusercontent.com/62225006/149210067-b90d9199-4b44-440f-9980-d5da1a4087e0.png)

**Comment by claudia-romano** [comment]
Hi there, have you used the HTML/SCSS/JS code we provide in the demo?
https://codyhouse.co/ds/components/app/percentage-bar

If yes, do you have any error in the console? 
Please make sure to provide more info on how to reproduce your bug so that we can look into it. Thanks.

**Comment by Zafer83** [comment]
> Hi there, have you used the HTML/SCSS/JS code we provide in the demo? https://codyhouse.co/ds/components/app/percentage-bar
> 
> If yes, do you have any error in the console? Please make sure to provide more info on how to reproduce your bug so that we can look into it. Thanks.

Hi i found my mistake i missed to copy the overall snippet for utility and this 

`<script>document.getElementsByTagName("html")[0].className += " js";</script>`

but i have a javascript error on the other issue  

copy to clipboard
#2
