### ISSUE TITLE
cd-copy-to-clipboard-changelog

### ISSUE THREAD

**Issue by Zafer83** [CodyHouse/cd-percentage-bar-changelog#2]
Copy to clipboard does not work the functionality is not given i think a js problem

**Comment by claudia-romano** [comment]
Please use the component GitHub folder to report bug:
https://github.com/CodyHouse/cd-copy-to-clipboard-changelog/issues

Also, please provide more info on how to reproduce the bug, otherwise we won't be able to help you fix it. Thanks!

**Comment by Zafer83** [comment]
pleaes see 

https://github.com/CodyHouse/cd-copy-to-clipboard-changelog/issues/1
